name: BujinkanMaaiHyoshiDojo
favicon: null
layout_spectrum: 0.37920228973962367
typography_spectrum: 0.11791232135146856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#1f1b1b'
    - '#6a6d5a'
    - '#e21619'
    - '#b7aa8f'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
